### ISSUE TITLE
[FYI] Added TS typings for your library

### ISSUE THREAD

**Issue by mhintzke** [itsfadnis/datadog-winston#7]
Hey @itsfadnis, 

Not actually an issue.

It took a few months for MS to finally approve my PR, but I got TypeScript typings for your library that my team and I are using in production. Just thought I would let you know. If you ever update your interfaces/models let me know and I would be happy to maintain my typings for you.

https://www.npmjs.com/package/@types/datadog-winston

**Comment by itsfadnis** [comment]
Sure, thank you @mhintzke
